#!/bin/bash

adb logcat -c
# adb logcat | grep -e toadlet -e OpenCV -e E/ -e QuadPhone -e GC_CONCURRENT
adb logcat | grep -e toadlet -e OpenCV -e E/ -e QuadPhone
# adb logcat | grep -e toadlet -e OpenCV -e QuadPhone 
