#!/bin/bash

adb logcat -c
# adb logcat | grep -e toadlet -e OpenCV -e E/ -e Rover -e GC_CONCURRENT
adb logcat | grep -e toadlet -e OpenCV -e VisionTestApp -e DEBUG 
# adb logcat | grep -e toadlet -e OpenCV -e Rover 
